JapaneseLearnSystem/Areas/Admin/Controllers/MemberManagementsController.cs
using JapaneseLearnSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JapaneseLearnSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "管理員")]
    public class MemberManagementsController : Controller
    {
        private readonly dbJapaneseLearnSystemContext _context;

        public MemberManagementsController(dbJapaneseLearnSystemContext context)
        {
            _context = context;
        }

        // GET: Admin/MemberManagements
        public async Task<IActionResult> Index()
        {
            var dbJapaneseLearnSystemContext = _context.Member.Include(m => m.Plan);
            return View(await dbJapaneseLearnSystemContext.ToListAsync());
        }

        // GET: Admin/MemberManagements/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.Plan)
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Admin/MemberManagements/Create
        public IActionResult Create()
        {
            ViewData["PlanID"] = new SelectList(_context.SubscriptionPlan, "PlanID", "PlanID");
            return View();
        }

        // POST: Admin/MemberManagements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberID,Name,Tel,PlanID,Email,Birthday")] Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlanID"] = new SelectList(_context.SubscriptionPlan, "PlanID", "PlanID", member.PlanID);
            return View(member);
        }

        // GET: Admin/MemberManagements/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            ViewData["PlanID"] = new SelectList(_context.SubscriptionPlan, "PlanID", "PlanID", member.PlanID);
            return View(member);
        }

        // POST: Admin/MemberManagements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MemberID,Name,Tel,PlanID,Email,Birthday")] Member member)
        {


            if (id != member.MemberID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.MemberID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlanID"] = new SelectList(_context.SubscriptionPlan, "PlanID", "PlanID", member.PlanID);
            return View(member);
        }

        // GET: Admin/MemberManagements/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.Plan)
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Admin/MemberManagements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var member = await _context.Member.FindAsync(id);
            if (member != null)
            {
                _context.Member.Remove(member);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(string id)
        {
            return _context.Member.Any(e => e.MemberID == id);
        }
    }
}

JapaneseLearnSystem/Areas/Admin/Views/MemberManagements/Create.cshtml
@model JapaneseLearnSystem.Models.Member

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberID" class="control-label"></label>
                <input asp-for="MemberID" class="form-control" />
                <span asp-validation-for="MemberID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlanID" class="control-label"></label>
                <select asp-for="PlanID" class ="form-control" asp-items="ViewBag.PlanID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JapaneseLearnSystem/Areas/Admin/Views/MemberManagements/Delete.cshtml
@model JapaneseLearnSystem.Models.Member

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plan.PlanID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JapaneseLearnSystem/Areas/Admin/Views/MemberManagements/Details.cshtml
@model JapaneseLearnSystem.Models.Member

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plan.PlanID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MemberID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

JapaneseLearnSystem/Areas/Admin/Views/MemberManagements/Edit.cshtml
@model JapaneseLearnSystem.Models.Member

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlanID" class="control-label"></label>
                <select asp-for="PlanID" class="form-control" asp-items="ViewBag.PlanID"></select>
                <span asp-validation-for="PlanID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JapaneseLearnSystem/Areas/Admin/Views/MemberManagements/Index.cshtml
@model IEnumerable<JapaneseLearnSystem.Models.Member>



@{
    ViewData["Title"] = "會員管理";
}

<h1>會員管理</h1>

<p>
    <a asp-area="Admin" asp-controller="MemberManagements" asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MemberID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlanID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlanID)
                </td>
                <td>
                    <a asp-area="Admin" asp-controller="MemberManagements" asp-action="Edit" asp-route-id="@item.MemberID">Edit</a> |
                    <a asp-area="Admin" asp-controller="MemberManagements" asp-action="Details" asp-route-id="@item.MemberID">Details</a> |
                    <a asp-area="Admin" asp-controller="MemberManagements" asp-action="Delete" asp-route-id="@item.MemberID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="mt-3">
    <a asp-action="QuestionCreate" asp-controller="QuestionManagements" asp-area="Admin" class="btn btn-primary">
        前往生成題目
    </a>

</div>